substitutions:
  device_name: "my-vivarium"
  friendly_name: "My Vivarium"
  area_name: "Vivarium"

  enable_jungle_dawn: "true"
  jungle_dawn_mac: !secret jungle_dawn_mac
  enable_prot5: "false"
  # prot5_mac: !secret prot5_mac  # Set enable_prot5 to "true" when connected.
  
  

packages:
  lumineze:
    url: https://github.com/I-am-shadowspawn/lumineze-controller-esphome
    ref: v1.0.0
    files:
      - packages/lumineze-controller.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key
